apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        # Image của bạn đã chứa sẵn SQL script
        image: 181040560981.dkr.ecr.ap-southeast-1.amazonaws.com/database:5 
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "ecommerce_db"
        - name: MYSQL_USER
          value: "ecommerceapp"
        - name: MYSQL_PASSWORD
          value: "StrongPa55WorD"
        
        # --- CẤU HÌNH TÀI NGUYÊN (QUAN TRỌNG) ---
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

        # --- TĂNG THỜI GIAN CHỜ (QUAN TRỌNG) ---
        startupProbe:
          tcpSocket:
            port: 3306
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10

        volumeMounts:
        # XÓA ConfigMap mount (để dùng SQL trong image)
        # XÓA PVC mount (để dùng ổ cứng tạm, tránh lỗi Pending)
        - name: mysql-local-storage
          mountPath: /var/lib/mysql

      volumes:
      # Thay PersistentVolumeClaim bằng emptyDir (Ổ tạm)
      - name: mysql-local-storage
        emptyDir: {} 

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: dev
spec:
  selector:
    app: mysql-db
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
