apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  storageClassName: gp2 # Loại ổ cứng mặc định của AWS EKS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: 181040560981.dkr.ecr.ap-southeast-1.amazonaws.com/database:5
        env:
        # Cấu hình mật khẩu (Ở môi trường thật nên dùng Secret, demo thì để text)
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "ecommerce_db"
        - name: MYSQL_USER
          value: "ecommerceapp"
        - name: MYSQL_PASSWORD
          value: "StrongPa55WorD"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        # 1. Mount ổ cứng thật vào nơi lưu data
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        # 2. Mount script SQL vào thư mục init để nó tự chạy lần đầu
        - name: mysql-init-scripts-vol
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim # Trỏ vào file storage ở trên
      - name: mysql-init-scripts-vol
        configMap:
          name: mysql-init-scripts # Lấy script từ ConfigMap (sẽ tạo ở Jenkins)
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db # Tên này phải trùng với tên trong code Spring Boot
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-db
  type: ClusterIP 