apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 181040560981.dkr.ecr.ap-southeast-1.amazonaws.com/product-service:4
          imagePullPolicy: Always
          ports:
            - containerPort: 8082 
          
      
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-db:3306/ecommerce_db?allowPublicKeyRetrieval=true&useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              value: "ecommerceapp"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "StrongPa55WorD"
            - name: USER_SERVICE_URL
              value: "http://user-service:8081/api/users/validate"

          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
            
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: product-service
  ports:
    - name: http
      port: 80  
      targetPort: 8082 
